# Generated by Django 3.1 on 2020-08-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200816_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_num',
            field=models.IntegerField(default=0),
        ),
    ]
