# Generated by Django 3.1 on 2020-08-16 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 5, 38, 10, 692447, tzinfo=utc)),
        ),
    ]
