# Generated by Django 3.1 on 2020-08-16 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200816_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
